#application config
app:
  name: tiklab-xpack
  path: ${APP_HOME}
spring:
  profiles:
    active: demo

#web config
server:
  port: 8080

#dal config

#dal config for mysql jdbc
jdbc:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://172.12.1.10:5432/tiklab_xpack?stringtype=unspecified
  username: postgres
  password: darth2020

DATA_HOME: ${user.home}/tiklab/${app.name}

eas:
  embbed:
    enable: false
  address: http://bac.eas.demo.tiklab.net

base:
  url: http://bac.eas.demo.tiklab.net
#dfs config
#dfs.server.enabled=false
dfs:
  client:
    url: 172.11.1.17:4000
    bucket: ${app.name}

#dcs server config

dcs:
  client:
    url: 172.11.1.17:5000
    bucket: ${app.name}

#dss config
#dss.server.enabled=false

dss:
  client:
    url: 172.11.1.17:6000
    bucket: ${app.name}

#plugin config
plugin.path: ${APP_HOME}/plugin

#rpc
ocs:
  address: http://172.11.1.11:8080


homes:
  address: http://172.11.1.11:8080
  return:
    path: ''

#licences config
licences:
  path: ${DATA_HOME}/data/dfs/default

db:
  path: 127.0.0.1:3306
  shell:
    path: ${APP_HOME}/script/create_db_local_02.sh


template:
  shell:
    path: ${APP_HOME}/script/create_db_local_02.sh

#file
file:
  path: http://file.dev.tiklab.net

repository:
  library: ${user.home}
  code: xpack
  address: "http://bac.xpack.demo.tiklab.net"