#application config
app:
  name: tiklab-xpack
  path: ${APP_HOME}

spring:
  config:
    import: optional:classpath:/config/${env:dev}/application.yaml
#web config
server:
  port: 8083

#dal config

#dal config for mysql jdbc
jdbc:
  driverClassName: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://172.27.46.219:3306/tiklab_xpack?characterEncoding=utf8&useSSL=false&serverTimezone=UTC
  username: root
  password: darth2020

DATA_HOME: ${user.home}/tiklab/${app.name}

#dfs config
#dfs.server.enabled=false
dfs:
  client:
    url: 101.132.162.74:4000
    bucket: ${app.name}

#dcs server config

dcs:
  client:
    url: 101.132.162.74:5000
    bucket: ${app.name}

#dss config
#dss.server.enabled=false

dss:
  client:
    url: 101.132.162.74:6000
    bucket: ${app.name}

#enable mysql
mysql:
  embbed:
    enable: false
  server:
    port: 3306
  database: tiklab_xpack

#eas config
eas:
  embbed:
    enable: true




#plugin config
plugin.path: ${APP_HOME}/plugin

#rpc
ocs:
  address: http://139.196.76.221:8080


homes:
  address: http://139.196.76.221:8080
  return:
    path: ''

#licences config
licences:
  path: ${DATA_HOME}/data/dfs/default



