#application config
app:
  name: tiklab-xpack
  path: ${APP_HOME}

spring:
  config:
    import: optional:classpath:/config/${env:dev}/application.yaml
#web config
server:
  port: 8080

#dal config

#dal config for mysql jdbc
jdbc:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://172.13.1.13:5432/tiklab_xpack?stringtype=unspecified
  username: postgres
  password: darth2020


postgresql:
  embbed:
    enable: true
  database: tiklab_xpack


DATA_HOME: ${user.home}/tiklab/${app.name}

#dfs config
#dfs.server.enabled=false
dfs:
  client:
    url: 101.132.162.74:4000
    bucket: ${app.name}

#dcs server config

dcs:
  client:
    url: 101.132.162.74:5000
    bucket: ${app.name}

#dss config
#dss.server.enabled=false

dss:
  client:
    url: 101.132.162.74:6000
    bucket: ${app.name}


#eas config
eas:
  embbed:
    enable: false
  address: http://bac.eas.tiklab.net




#plugin config
plugin.path: ${APP_HOME}/plugin

#rpc
ocs:
  address: http://139.196.76.221:8080


homes:
  address: http://139.196.76.221:8080
  return:
    path: ''

#licences config
licences:
  path: ${DATA_HOME}/data/dfs/default

#file
file:
  path: http://file.tiklab.net

repository:
  library: ${user.home}
  code: xpack
  address: ""
